"""
Django settings for pr_eni project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
from django.core.management.utils import get_random_secret_key
from django.core.exceptions import ImproperlyConfigured
from urllib.parse import urlsplit
import os
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY") or get_random_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = []
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append (RENDER_EXTERNAL_HOSTNAME)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app_autenticacion',
    'app_convocatorias',
    'app_inscripciones',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pr_eni.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pr_eni.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",conn_max_age=600, ssl_require=not DEBUG)
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
if not DEBUG:
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

SUPABASE_STORAGE_SETTINGS = {
    'access_key': os.environ.get('SUPABASE_ACCESS_KEY'),
    'secret_key': os.environ.get('SUPABASE_SECRET_KEY'),
    'bucket': os.environ.get('SUPABASE_BUCKET'),
    'endpoint': os.environ.get('SUPABASE_ENDPOINT'),
}
supabase_values_present = [bool(value) for value in SUPABASE_STORAGE_SETTINGS.values()]

if any(supabase_values_present) and not all(supabase_values_present):
    raise ImproperlyConfigured(
        'Define all four SUPABASE storage environment variables together.'
    )

USE_SUPABASE_STORAGE = all(supabase_values_present)
if (not DEBUG or RENDER_EXTERNAL_HOSTNAME) and not USE_SUPABASE_STORAGE:
    raise ImproperlyConfigured(
        'Supabase storage environment variables are required in production.'
    )

STATICFILES_BACKEND = (
    'whitenoise.storage.CompressedManifestStaticFilesStorage'
    if not DEBUG
    else 'django.contrib.staticfiles.storage.StaticFilesStorage'
)

STORAGES = {
    'default': {
        'BACKEND': 'storages.backends.s3.S3Storage'
        if USE_SUPABASE_STORAGE
        else 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': STATICFILES_BACKEND,
    },
}

if USE_SUPABASE_STORAGE:
    endpoint_host = urlsplit(SUPABASE_STORAGE_SETTINGS['endpoint']).hostname or ''
    supabase_s3_suffix = '.storage.supabase.co'
    if not endpoint_host.endswith(supabase_s3_suffix):
        raise ImproperlyConfigured(
            'SUPABASE_ENDPOINT must use the *.storage.supabase.co hostname.'
        )

    project_ref = endpoint_host[:-len(supabase_s3_suffix)]
    public_domain = (
        f'{project_ref}.supabase.co/storage/v1/object/public/'
        f"{SUPABASE_STORAGE_SETTINGS['bucket']}"
    )
    MEDIA_URL = f'https://{public_domain}/'

    AWS_ACCESS_KEY_ID = SUPABASE_STORAGE_SETTINGS['access_key']
    AWS_SECRET_ACCESS_KEY = SUPABASE_STORAGE_SETTINGS['secret_key']
    AWS_STORAGE_BUCKET_NAME = SUPABASE_STORAGE_SETTINGS['bucket']
    AWS_S3_ENDPOINT_URL = SUPABASE_STORAGE_SETTINGS['endpoint']
    AWS_S3_REGION_NAME = 'us-east-1'
    AWS_S3_ADDRESSING_STYLE = 'path'
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_CUSTOM_DOMAIN = public_domain
    AWS_QUERYSTRING_AUTH = False
    AWS_DEFAULT_ACL = None


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
